# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/cygwin/home/redal/plasma/vhdl/plasma_hw.cache/wt [current_project]
set_property parent.project_path C:/cygwin/home/redal/plasma/vhdl/plasma_hw.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/cygwin/home/redal/plasma/vhdl/plasma_hw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/cygwin/home/redal/plasma/vhdl/mlite_pack.vhd
  C:/cygwin/home/redal/plasma/vhdl/shifter.vhd
  C:/cygwin/home/redal/plasma/vhdl/reg_bank.vhd
  C:/cygwin/home/redal/plasma/vhdl/pipeline.vhd
  C:/cygwin/home/redal/plasma/vhdl/pc_next.vhd
  C:/cygwin/home/redal/plasma/vhdl/mult.vhd
  C:/cygwin/home/redal/plasma/vhdl/mem_ctrl.vhd
  C:/cygwin/home/redal/plasma/vhdl/control.vhd
  C:/cygwin/home/redal/plasma/vhdl/bus_mux.vhd
  C:/cygwin/home/redal/plasma/vhdl/alu.vhd
  C:/cygwin/home/redal/plasma/vhdl/uart.vhd
  C:/cygwin/home/redal/plasma/vhdl/mlite_cpu.vhd
  C:/cygwin/home/redal/plasma/vhdl/eth_dma.vhd
  C:/cygwin/home/redal/plasma/vhdl/cache.vhd
  C:/cygwin/home/redal/plasma/vhdl/ram_image.vhd
  C:/cygwin/home/redal/plasma/vhdl/plasma.vhd
  C:/Users/redal/TDs/TP/SE/TP1/TP1.srcs/sources_1/imports/TP1/Clkdiv.vhd
  C:/cygwin/home/redal/plasma/vhdl/plasma_hw.srcs/sources_1/new/plasma_basys3.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/cygwin/home/redal/plasma/vhdl/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/cygwin/home/redal/plasma/vhdl/Basys3_Master.xdc]


synth_design -top plasma_basys3 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef plasma_basys3.dcp

catch { report_utilization -file plasma_basys3_utilization_synth.rpt -pb plasma_basys3_utilization_synth.pb }
