# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma_hw.cache/wt [current_project]
set_property parent.project_path D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma_hw.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma_hw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.dcp
set_property used_in_implementation false [get_files D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.dcp]
read_vhdl -library xil_defaultlib {
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/mlite_pack.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/shifter.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/reg_bank.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/pipeline.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/pc_next.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/mult.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/mem_ctrl.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/control.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/bus_mux.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/alu.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/uart.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/ram_image.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/mlite_cpu.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/eth_dma.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/cache.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/clk50.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/gestion_an.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/clk190.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/hex7seg.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/mux_7.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/cpt.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/Clkdiv.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/7seg/7seg_top.vhd
  D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/plasma_hw.srcs/sources_1/new/plasma_basys3.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/cours/mea4/systeme_emb/projet/syst_embarque/home/plasma/vhdl/Basys3_Master.xdc]


synth_design -top plasma_basys3 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef plasma_basys3.dcp

catch { report_utilization -file plasma_basys3_utilization_synth.rpt -pb plasma_basys3_utilization_synth.pb }
