# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/cygwin/home/simon/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.xci
# IP: The module: 'RAM_PROGRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cygwin/home/simon/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_PROGRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/cygwin/home/simon/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.xci
# IP: The module: 'RAM_PROGRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cygwin/home/simon/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_PROGRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
