# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/cygwin/home/plasma/vhdl/plasma_hw.cache/wt [current_project]
set_property parent.project_path C:/cygwin/home/plasma/vhdl/plasma_hw.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/cygwin/home/plasma/vhdl/plasma_hw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.xci
set_property is_locked true [get_files c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1 -new_name RAM_PROGRAM -ip [get_ips RAM_PROGRAM]]

if { $cached_ip eq {} } {

synth_design -top RAM_PROGRAM -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix RAM_PROGRAM_ RAM_PROGRAM.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ RAM_PROGRAM_stub.v
 lappend ipCachedFiles RAM_PROGRAM_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ RAM_PROGRAM_stub.vhdl
 lappend ipCachedFiles RAM_PROGRAM_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ RAM_PROGRAM_sim_netlist.v
 lappend ipCachedFiles RAM_PROGRAM_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ RAM_PROGRAM_sim_netlist.vhdl
 lappend ipCachedFiles RAM_PROGRAM_sim_netlist.vhdl

 config_ip_cache -add -dcp RAM_PROGRAM.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips RAM_PROGRAM]
}

rename_ref -prefix_all RAM_PROGRAM_

write_checkpoint -force -noxdef RAM_PROGRAM.dcp

catch { report_utilization -file RAM_PROGRAM_utilization_synth.rpt -pb RAM_PROGRAM_utilization_synth.pb }

if { [catch {
  file copy -force C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1/RAM_PROGRAM.dcp c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1/RAM_PROGRAM.dcp c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1/RAM_PROGRAM_stub.v c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1/RAM_PROGRAM_stub.vhdl c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1/RAM_PROGRAM_sim_netlist.v c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/cygwin/home/plasma/vhdl/plasma_hw.runs/RAM_PROGRAM_synth_1/RAM_PROGRAM_sim_netlist.vhdl c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/cygwin/home/plasma/vhdl/plasma_hw.ip_user_files/ip/RAM_PROGRAM]} {
  catch { 
    file copy -force c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_stub.v C:/cygwin/home/plasma/vhdl/plasma_hw.ip_user_files/ip/RAM_PROGRAM
  }
}

if {[file isdir C:/cygwin/home/plasma/vhdl/plasma_hw.ip_user_files/ip/RAM_PROGRAM]} {
  catch { 
    file copy -force c:/cygwin/home/plasma/vhdl/plasma_hw.srcs/sources_1/ip/RAM_PROGRAM/RAM_PROGRAM_stub.vhdl C:/cygwin/home/plasma/vhdl/plasma_hw.ip_user_files/ip/RAM_PROGRAM
  }
}
