cd C:\Users\redal\OneDrive\Bureau\Study\SE
cd Users\redal\OneDrive\Bureau\Study\SE
cd \Users\redal\OneDrive\Bureau\Study\SE
cd C:/Users/redal/OneDrive/Bureau/Study/SE
cd plasma
export PATH=/cygdrive/c/Users/redal/OneDrive/Bureau/Study/SE/plasma/gccmips_elf:$PATH
make new_app
export PATH=</cygdrive/c/Users/redal/OneDrive/Bureau/Study/SE>/plasma/gccmips_elf:$PATH
export PATH=/cygdrive/c/Users/redal/OneDrive/Bureau/Study/SE/plasma/gccmips_elf:$PATH
export PATH=/plasma/gccmips_elf:$PATH
make new_app
export PATH=C:/Users/redal/OneDrive/Bureau/Study/SE/plasma/gccmips_elf:$PATH
make new_app
$export PATH=/home/redal/plasma/gccmips_elf:$PATH
redal@LAPTOP-6FHR77T6 ~
$ cd Users\redal\OneDrive\Bureau\Study\SE
cd /home/redal/plasma/
$export PATH=/home/redal/plasma/gccmips_elf:$PATH
make new_app
cd ../
cd ../
../
cd ../
cd ../
cd /home/redal/plasma
$export PATH=C:/cygwin/home/redal/plasma/gccmips_elf:$PATH
make new_app

$export PATH=/home/redal/plasma/gccmips_elf:$PATH
cd /tools
cd tools
make new_app
cd /home/redal/plasma
cd /home/redal/plasm
cd tools
make new_app
make new_app
make new_app
make new_app
$export PATH=/home/redal/plasma/gccmips_elf:$PATH
make new_app
cd tools
cd /home/redal/plasma
cd tools
make new_app
cd /home/redal/plasma
make new_app
cd tools
make new_app
make new_app
make new_app
which gcc
$export PATH=/home/redal/plasma/gccmips_elf:$PATH
export PATH=<chemin_vers_répertoire_de_travail>/plasma/gccmips_elf:$PATH
$export PATH=home/redal/plasma/gccmips_elf:$PATH
$export PATH=home/redal/plasma/gccmips_elf:$PAT
cd /home/redal/plasma
which gccfu
$export PATH=home/redal/plasma/gccmips_elf:$PATH
export PATH=home/redal/plasma/gccmips_elf:$PATH
fuck u
which gcc

cd tools/
make new_app
make new_app
make new_app
ls
make new_app
which gcc
export PATH=home/redal/plasma/gccmips_elf:$PATH
which gcc
export PATH=/home/redal/plasma/gccmips_elf:$PATH
which gcc
make new_app
sudo make new_app.
make new_app
sudo make new_app
make new_app
make new_app.c
make new_app.c
make new_app
make new_app
make new_app
which gcc
make new_app
make new_app
make new_app
cd /home/redal/plasma
cd tools
which gcc
export PATH=/home/redal/plasma/gccmips_elf:$PATH
which gcc
make new_app
make new_app
make new_app
make new_app
cd /home/redal/plasma/tools
which gcc
export PATH=/home/redal/plasma/gccmips_elf:$PATH
which gcc
make new_app
make new_app
make new_app
which gcc
export PATH=/home/redal/plasma/gccmips_elf:$PATH
which gcc
cd /home/redal/plasma/tools
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led
make test_led

make test_led
make test_led
bin/mlite.exe test.bin
make toimage
make toimage
make toimage
make test_led
bin/mlite.exe test.bin
make toimage
make test_led
make toimage
make test_led
make toimage
make test_led
make toimage
make test_led
make toimage
make test_led
make test_led
make toimage
cd /home/redal/plasma/tools
make test_led
bin/mlite.exe test.bin
make toimage

make test_led
export PATH=/home/redal/plasma/gccmips_elf:$PATH
which gcc
make test_led
make toimage
make test_led
make toimage
make test_led
make test_led
make toimage
make test_led
make toimage
make test_led
make toimage
make toimage
export PATH=/home/redal/plasma/gccmips_elf:$PATH
which gcc
cd /home/redal/plasma/tools
make test_led
bin/mlite.exe test.bin
make toimage
